In [4]:
import numpy as np
import pandas as pd

In [5]:
np.random.seed(77)

mul_vec1=np.array([0,0,0])
cov_mat1=np.array([[1,0,0], [0,1,0], [0,0,1]])
class1_sample=np.random.multivariate_normal(mul_vec1, cov_mat1, 20)

df=pd.DataFrame(class1_sample, columns=['feature1', 'feature2', 'feature3'])
df['target']=1

mul_vec2=np.array([1,1,1])
cov_mat2=np.array([[1,0,0], [0,1,0], [0,0,1]])
class1_sample=np.random.multivariate_normal(mul_vec2, cov_mat2, 20)

df1=pd.DataFrame(class1_sample, columns=['feature1', 'feature2', 'feature3'])
df1['target']=0

df=df.append(df1, ignore_index=True)
df=df.sample(40)




<ipython-input-5-2999072a5a1e>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(df1, ignore_index=True)


In [6]:
df.head()

feature1  feature2  feature3  target
12  0.197381  0.275060 -0.879132       1
4  -1.049095 -0.976578 -0.639051       1
20  0.008580  1.107351  0.455209       0
2   0.275548 -1.575805  1.568397       1
0   0.224445  0.661531 -0.579758       1

In [7]:
import plotly.express as px

fig= px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
                   color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()

In [8]:
# step 1 - Applying Standard Scaler for mean centering
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

df.iloc[:, 0:3]=scaler.fit_transform(df.iloc[:, 0:3])

In [9]:
# Step 2 - Finding covariance matrix
covariance_matrix=np.cov([df.iloc[:, 0], df.iloc[:, 1], df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.31971451 0.44685281]
 [0.31971451 1.02564103 0.36268122]
 [0.44685281 0.36268122 1.02564103]]


In [10]:
# step 3 - Eigen value and vector

eigen_values, eigen_vectors=np.linalg.eig(covariance_matrix)

In [11]:
eigen_values

array([1.7810338 , 0.57399339, 0.72189589])

In [12]:
eigen_vectors

array([[-0.58605038, -0.63703646,  0.50072897],
       [-0.53866052, -0.15534485, -0.82807779],
       [-0.60530141,  0.75501823,  0.25210648]])

In [13]:
principal_component=eigen_vectors[0:2]
principal_component

array([[-0.58605038, -0.63703646,  0.50072897],
       [-0.53866052, -0.15534485, -0.82807779]])

In [14]:
transformed_df=np.dot(df.iloc[:, 0:3], principal_component.T)
new_df=pd.DataFrame(transformed_df, columns=['pc1', 'pc2'])
new_df['target']=df['target'].values
new_df.head()

pc1       pc2  target
0 -0.535363  1.227141       1
1  0.947218  1.832407       1
2 -0.321051  0.225609       0
3  1.566754 -0.344879       1
4 -0.638374  0.940780       1

In [16]:
new_df['target']=new_df['target'].astype('str')
fig=px.scatter(x=new_df['pc1'],
               y=new_df['pc2'],
               color=new_df['target'],
               color_discrete_sequence=px.colors.qualitative.G10)

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                   selector=dict(mode='marker'))

fig.show()